[package]
name = "pop_quiz_sol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reikna = "0.12.3"
num-bigint = "0.4.4"
modinverse = "0.1.1"
num-traits = "0.2.17"
rand = "0.8.5"
hex = "0.4.3"